export const Constants = {
    SECRET_KEY: "ImmobileApp2021",
    PATTERN_FIELD_WITHOUT_SPECIAL_CHARACTERS : /[a-zA-Z]+$/g,
    PATTERN_FIELD_EMAIL: /[a-zA-Z0-9]+@\D+\.(com|br)$/g,
    PATTERN_FIELD_CPF_CNPJ_MASKED: /((\d{3}\.){2}\d{3}-\d{2})|(\d{2}(\.\d{3}){2}.\d{4}\.\d{2})/g,
    PATTERN_FIELD_PHONE: /\(\d{2}\)\d{5}-\d{4}/g,
    PATTERN_FIELD_NUMBER: /[0-9]+/g,
    PATTERN_FIELD_DATE: /(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])/g,
    ROLE_CRUD_CONTRACT: "CRUD_CONTRACT",
    INVALID_COMMON_MESSAGE: "Verifique as seguintes condições:",
    INVALID_FIELD_EMPTY: "Campo não informado ou vazio.",
    INVALID_FIELD_100_CHARACTERS: "Máximo de 100 caracteres são permitidos.",
    INVALID_FIELD_255_CHARACTERS: "Máximo de 255 caracteres são permitidos.",
    INVALID_PATTERN_FIELD_WITHOUT_SPECIAL_CHARACTERS: "Caracteres especiais como @,#,$,%,-,/,' não são permitidos.",
    INVALID_PATTERN_FIELD_EMAIL: "Email fora do padrão com @server.com ou @server.br",
    INVALID_PATTERN_FIELD_CPF_CNPJ: "CPF/CNPJ fora de padrão.",
    INVALID_PATTERN_FIELD_PHONE: "Telefone fora do formato padrão.",
    INVALID_EXISTING_USER: "Usuário já registrado no sistema.",
    INVALID_EXISTING_ENTITY: "O sistema já possui uma entidade com os dados informados!",
    INVALID_IDENTIFIER_NOT_PROVIDED: "Identificador não informado!",
    INVALID_LOGIN_FIELDS: "Email ou Senha inválidos! Verifique se os campos estão com no máximo 255 caracteres ou se o email informado é válido.",
    INVALID_LOGIN_USER_NOT_FOUND: "Nenhum usuário com as informações repassadas foi encontrado.",
    INVALID_LOGIN_PASSWORD_PROVIDED: "Senha informada está incorreta.",
    INVALID_TOKEN_INVALID: "Token de acesso não informado ou inválido!",
    INVALID_RECOVERY_EMAIL: "Email inválido!",
    INVALID_REQUEST_AUTHORIZATION_HEADER_NOT_FOUND: "Informações de autorização não informados!",
    INVALID_REQUEST_AUTHORIZATION_EXPIRED_TOKEN: "Token expirado ou inválido!",
    SUCCESS_MESSAGE_OPERATION: "Operação realizada com sucesso!"
}